export const brandsAndModels = {
  "Alfa Romeo": [
    "156",
    "159",
    "4C",
    "Brera",
    "GIULIA",
    "Giulietta",
    "Mito",
    "Spider",
    "Stelvio",
  ],
  "Aston Martin": [
    "DB11",
    "DB7",
    "DB9",
    "DBS",
    "DBX",
    "Rapide",
    "V8 Vantage",
    "Vanquish",
    "Vantage",
    "Virage",
  ],
  "奧迪/Audi": [
    "A1",
    "A1 Sportback",
    "A3 5D",
    "A3 Sedan",
    "A3 Sportback",
    "A4 Allroad",
    "A4 Avant",
    "A4 Sedan",
    "A5",
    "A5 Coupe",
    "A5 Sportback",
    "A6 Allroad",
    "A6 Avant",
    "A6 Sedan",
    "A7",
    "A7 Sportback",
    "A8",
    "A8L",
    "e-tron",
    "Q2",
    "Q3",
    "Q3 Sportback",
    "Q5",
    "Q5 Sportback",
    "Q7",
    "Q8",
    "R8",
    "R8 Coupe",
    "R8 Spyder",
    "RS 3",
    "RS 4",
    "RS 5 Coupe",
    "RS 5 Sportback",
    "RS 6",
    "RS 7",
    "RS Q3",
    "S3",
    "S3 Sportback",
    "S4 Avant",
    "S4 Sedan",
    "S5 Coupe",
    "S5 Sportback",
    "S6 Avant",
    "S7 Sportback",
    "S8",
    "SQ2",
    "SQ5",
    "SQ7",
    "TT",
    "TT RS",
    "TTS",
  ],
  Austin: ["Mini Mayfair"],
  Abarth: [
    "500 Abarth",
    "595 Competizione",
    "595 Esseesse",
    "595 Scorpioneoro",
    "595C Monster Energy Yamaha",
    "Abarth 695",
    "695 TRIBUTO FERRARI",
    "Abarth 595",
  ],
  Bentley: [
    "Bentayga",
    "Continental",
    "Continental Flying Spur",
    "Continental GT",
    "Continental GT Speed",
    "Continental GT3-R",
    "Continental GTC",
    "Continental Supersports",
    "Flying Spur",
    "Mulsanne",
  ],
  BMW: [
    "1-Series",
    "2-Series",
    "3-Series",
    "4-Series",
    "5-Series",
    "6-Series",
    "7-Series",
    "8-Series",
    "Alpina",
    "M",
    "X1",
    "X2",
    "X3",
    "X4",
    "X5",
    "X6",
    "X7",
    "Z1",
    "Z4",
    "i",
  ],
  BRABUS: [],
  "Citroen/雪鐵龍": [
    "Berlingo短軸版",
    "Berlingo長軸版",
    "C 5",
    "C2",
    "DS 3",
    "Saxo",
  ],
  "Ferrai/法拉利": [
    "296GTB",
    "458 Italia",
    "458 speciale",
    "458 Spider",
    "488",
    "488 Spider",
    "575",
    "599",
    "599 GTB Fiorano",
    "California",
    "California T",
    "F12 Berlinetta",
    "F430",
    "F8 Spider",
    "F8 Tributo",
    "FF",
    "GTC4Lusso",
    "Portofino",
    "Roma",
    "SF90 Stradale",
  ],
  Fiat: ["Fiat500", "500C", "500", "500X", "Panda"],
  Infiniti: [
    "EX35",
    "EX37",
    "FX",
    "FX35",
    "FX45",
    "G Convertible",
    "G25",
    "G35",
    "G37",
    "JX35",
    "M25",
    "M35",
    "M37",
    "Q30",
    "Q50",
    "Q60",
    "Q70",
    "QX30",
    "QX4",
    "QX50",
    "QX55",
    "QX60",
    "QX70",
  ],
  Jaguar: [
    "E-Pace",
    "F-Pace",
    "F-Type",
    "F-Type Convertible",
    "F-Type Coupe",
    "I-Pace",
    "S-Type",
    "Sovereign",
    "Vanden Plas",
    "X-Type",
    "XE",
    "XF",
    "XF Sportbrake",
    "XFR",
    "XJ",
    "XJ6",
    "XJ8",
    "XJL",
    "XK",
  ],
  "Jeep/吉普": ["Cherokee", "Gladiator", "Grand Cherokee", "Wrangler"],
  "Lamborghini/藍寶堅尼": [
    "Aventador",
    "Gallardo",
    "Gallardo Spyder LP560-4",
    "Huracan",
    "Huracan EVO",
    "Huracan LP580-2",
    "Huracan LP610 - 4",
    "Huracan Performante",
    "Huracan Performante Spyder",
    "Huracan STO",
    "LP560-4",
    "Urus",
  ],
  "Land Rover": [
    "Defender",
    "Discovery",
    "Discovery Sport",
    "Freelander",
    "Range Rover",
    "Range Rover Evoque",
    "Range Rover Evoque Coupe",
    "Range Rover Sport",
    "Range Rover Velar",
  ],
  //   "Lexus",
  //   "Lotus/蓮花",
  //   "Mercedes-Benz/賓士",
  //   "Maserati/瑪莎拉蒂",
  //   "Mini",
  //   "McLaren/麥拉倫",
  //   "Opel/歐寶",
  //   "Peugeot",
  //   "Porsche/保時捷",
  //   "Rolls-Royce/勞斯萊斯",
  //   "Skoda",
  //   "Smart",
  //   "Tesla/特斯拉",
  //   "Volvo",
  //   "Toyota",
  //   "Nissan",
  //   "Mitsubishi",
  //   "VW",
  // 添加更多品牌和車型
};

export const Colorlist = ["紅色", "黑色", "藍色", "灰色", "白色", "銀色"];
